/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.5.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ProposalFactoryExecuteMsg = {
  create_proposal: {
    config: ProposalConfig;
    [k: string]: unknown;
  };
} | {
  modify_config: {
    min_quorum_fraction?: Decimal | null;
    owner?: string | null;
    proposal_code_id?: number | null;
    proposal_cost?: Asset | null;
    [k: string]: unknown;
  };
} | {
  withdraw_funds: {
    asset: Asset;
    [k: string]: unknown;
  };
};
export type Decimal = string;
export type Uint128 = string;
export type AssetInfo = {
  token: {
    contract_addr: string;
    [k: string]: unknown;
  };
} | {
  native_token: {
    denom: string;
    [k: string]: unknown;
  };
};
export interface ProposalConfig {
  close_time: number;
  nft_contract: string;
  options: ProposalOption[];
  proposal_uri: string;
  quorum_fraction: Decimal;
  title: string;
  [k: string]: unknown;
}
export interface ProposalOption {
  id: number;
  name: string;
  [k: string]: unknown;
}
export interface Asset {
  amount: Uint128;
  info: AssetInfo;
  [k: string]: unknown;
}
export interface ProposalFactoryInstantiateMsg {
  config: ProposalFactoryConfig;
  [k: string]: unknown;
}
export interface ProposalFactoryConfig {
  min_quorum_fraction: Decimal;
  nft_contract: string;
  proposal_code_id: number;
  proposal_cost: Asset;
  [k: string]: unknown;
}
export type ProposalFactoryQueryMsg = {
  status: {
    [k: string]: unknown;
  };
} | {
  proposals: {
    limit?: number | null;
    start_idx?: number | null;
    [k: string]: unknown;
  };
};
